# SPDX-License-Identifier: MIT
"""Test-only ``keyCommand``. Prints the throw-away test key (generated by the test run and passed
through the environment of the test process, never stored) or misbehaves on purpose.

usage: keycmd.py ok|exit1|garbage|short|long|sleep|no-op-env|noisy-fail
"""

import base64
import os
import sys
import time

mode = sys.argv[1] if len(sys.argv) > 1 else "ok"
key = os.environ.get("NBP_SAFE_TEST_KEY", "")

if mode == "ok":
    sys.stdout.write(key + "\n")
elif mode == "exit1":
    sys.stdout.write(key + "\n")  # a valid key, but the command reports failure
    sys.exit(1)
elif mode == "garbage":
    sys.stdout.write("this is not base64 !!!\n")
elif mode == "short":
    sys.stdout.write(base64.b64encode(os.urandom(32)).decode() + "\n")
elif mode == "long":
    sys.stdout.write("A" * 100_000)
elif mode == "sleep":
    time.sleep(120)
elif mode == "no-op-env":  # the key only when no OP_* variable reached this process
    if any(name.upper().startswith("OP_") for name in os.environ):
        sys.exit(3)
    sys.stdout.write(key + "\n")
elif mode == "noisy-fail":  # a failure whose stderr carries a token-looking value
    sys.stderr.write("[ERROR] boom: " + os.environ.get("NBP_SAFE_TEST_NOISE", "") + "\n")
    sys.exit(1)
else:
    sys.exit(2)
