# SPDX-License-Identifier: MIT
"""Coexistence matrix for the hooks: a hook already in the hooks directory, husky-style
``core.hooksPath``, the pre-commit framework, a git without config hooks (shim fallback),
``--no-verify``; install / uninstall safety; ``autoUnlock`` and the rule that hooks never ask the
password manager on their own."""

from __future__ import annotations

import hashlib
import json
import stat
import sys
from pathlib import Path

import pytest

from nbp_git_safe import crypto, hooks
from tests import helpers
from tests.helpers import NbpRepo
from tests.integration.conftest import Env
from tests.integration.guardkit import commit, first_protected, prune_unreachable, staged

FOREIGN_HAND_WRITTEN = (
    '#!/bin/sh\necho "ran $0" >> "$(git rev-parse --git-dir)/foreign-ran"\nexit 0\n'
)
FOREIGN_FRAMEWORK = (
    "#!/usr/bin/env bash\n"
    "# File generated by pre-commit: https://pre-commit.com\n"
    "# ID: 138fd403232d2ddd5efb44317e38bf03\n"
    'echo "ran framework" >> "$(git rev-parse --git-dir)/foreign-ran"\n'
    "exit 0\n"
)


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_hook(directory: Path, event: str, text: str) -> Path:
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / event
    path.write_bytes(text.encode("utf-8"))
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path


def foreign_runs(repo: NbpRepo) -> int:
    marker = repo.path / ".git" / "foreign-ran"
    return len(marker.read_text().splitlines()) if marker.exists() else 0


def config_hooks(repo: NbpRepo) -> list[str]:
    out = repo.raw("config", "--local", "--get-regexp", r"^hook\.").stdout
    return [line for line in out.splitlines() if line]


# --------------------------------------------------------------------- config hooks


def test_init_installs_the_five_hooks_by_config_and_is_idempotent(env: Env) -> None:
    repo = env.repo
    first = repo.cli("init")
    assert first.code == 0 and "git config hooks: pre-commit, pre-push" in first.err
    before = config_hooks(repo)
    assert len(before) == 10  # a command and an event per hook
    for event in hooks.EVENTS:
        assert f"hook.nbp-git-safe-{event}.command" in "\n".join(before)
        assert hooks.hook_name(event) in repo.sh("hook", "list", event).split()
    assert not any((repo.path / ".git" / "hooks" / e).exists() for e in hooks.EVENTS)
    assert repo.cli("init").code == 0
    assert config_hooks(repo) == before  # idempotent: no duplicate events or commands


def test_hook_command_is_a_quoted_oneliner_for_this_interpreter(env: Env) -> None:
    env.repo.cli("init")
    command = env.repo.sh("config", "--local", "hook.nbp-git-safe-pre-commit.command").strip()
    assert command == hooks.hook_command("pre-commit")
    assert command.endswith(" -I -m nbp_git_safe hook pre-commit")
    assert command.startswith("'") and " -I " in command  # quoted path, isolated mode


@pytest.mark.parametrize(
    "script", [FOREIGN_HAND_WRITTEN, FOREIGN_FRAMEWORK], ids=["own", "framework"]
)
def test_foreign_hooks_in_the_hooks_dir_run_alongside_and_stay_untouched(
    env: Env, script: str
) -> None:
    repo = env.repo
    hooks_dir = repo.path / ".git" / "hooks"
    pre = write_hook(hooks_dir, "pre-commit", script)
    post = write_hook(hooks_dir, "post-commit", script)
    digests = {pre: sha(pre), post: sha(post)}
    assert repo.cli("init").code == 0
    assert {pre: sha(pre), post: sha(post)} == digests
    repo.sh("add", "-A")
    result = commit(repo, "both hooks run")
    assert result.returncode == 0, result.stderr
    assert foreign_runs(repo) == 2  # the foreign pre-commit and post-commit both ran ...
    assert env.has_vault()  # ... and so did ours (post-commit sealed)
    # ours still blocks even though the foreign hook says yes
    repo.write("reports/blocked.csv", "x")
    repo.sh("add", "-f", "reports/blocked.csv")
    assert commit(repo, "nope").returncode != 0
    repo.sh("restore", "--staged", "--", "reports/blocked.csv")
    prune_unreachable(repo)
    # a foreign hook that fails blocks too: we do not swallow it
    write_hook(hooks_dir, "pre-commit", "#!/bin/sh\nexit 1\n")
    assert commit(repo, "foreign says no", "--allow-empty").returncode != 0
    write_hook(hooks_dir, "pre-commit", script)
    # uninstall removes ours only
    assert repo.cli("uninstall", "--yes").code == 0
    assert {pre: sha(pre), post: sha(post)} == digests
    assert config_hooks(repo) == []
    repo.assert_no_leak(env.bare)


def test_husky_style_hooks_path_is_respected_and_never_written_to(env: Env) -> None:
    repo = env.repo
    husky = repo.path / ".husky"
    script = write_hook(husky, "pre-commit", FOREIGN_HAND_WRITTEN)
    repo.sh("config", "--local", "core.hooksPath", ".husky")
    digest = sha(script)
    result = repo.cli("init")
    assert result.code == 0 and "git config hooks" in result.err
    assert sorted(p.name for p in husky.iterdir()) == ["pre-commit"]  # nothing added there
    assert sha(script) == digest
    repo.sh("add", "-A")
    assert commit(repo, "with husky").returncode == 0
    assert foreign_runs(repo) == 1 and env.has_vault()
    repo.write("reports/x.csv", "x")
    repo.sh("add", "-f", "reports/x.csv")
    assert commit(repo, "blocked").returncode != 0
    repo.sh("restore", "--staged", "--", "reports/x.csv")
    prune_unreachable(repo)
    report = repo.cli("doctor")
    assert report.code == 0 and "core.hooksPath is set" in report.out
    assert repo.cli("uninstall", "--yes").code == 0
    assert sorted(p.name for p in husky.iterdir()) == ["pre-commit"] and sha(script) == digest


# ------------------------------------------------------------------- shim fallback


@pytest.fixture
def no_config_hooks(monkeypatch: pytest.MonkeyPatch) -> None:
    """Pretend git is too old for hooks by config (``init`` then falls back to shims). The hooks
    themselves run in separate processes with the real code."""
    monkeypatch.setattr(hooks, "MIN_GIT", (99, 0))


def test_shim_fallback_installs_only_where_nothing_exists(env: Env, no_config_hooks: None) -> None:
    repo = env.repo
    hooks_dir = repo.path / ".git" / "hooks"
    foreign = write_hook(hooks_dir, "pre-push", FOREIGN_HAND_WRITTEN)
    digest = sha(foreign)
    result = repo.cli("init")
    assert result.code == 0
    assert "hook-file shims: pre-commit, post-commit, post-merge, post-checkout" in result.err
    assert "NOT installed: pre-push" in result.err
    assert "a hook file that is not ours exists" in result.err
    assert sha(foreign) == digest  # never overwritten
    assert config_hooks(repo) == []
    for event in ("pre-commit", "post-commit", "post-merge", "post-checkout"):
        text = (hooks_dir / event).read_text()
        assert hooks.is_our_shim(text, event) and text == hooks.shim_text(event)
    statuses = {s.event: s for s in hooks.inspect_hooks(*_git_repo(repo))}
    assert statuses["pre-commit"].ok and statuses["pre-commit"].mechanism == "shim"
    assert not statuses["pre-push"].ok and statuses["pre-push"].foreign_file
    before = {e: sha(hooks_dir / e) for e in ("pre-commit", "post-commit")}
    assert repo.cli("init").code == 0  # idempotent
    assert {e: sha(hooks_dir / e) for e in before} == before


def _git_repo(repo: NbpRepo):  # type: ignore[no-untyped-def]
    from nbp_git_safe.gitutil import discover

    found, git = discover(repo.path, repo.git.env)
    return git, found


def test_shim_hooks_really_guard_and_seal(env: Env, no_config_hooks: None) -> None:
    repo = env.repo
    assert repo.cli("init").code == 0
    repo.sh("add", "-A")
    assert commit(repo, "baseline via shims").returncode == 0, "shim pre-commit must pass"
    assert env.has_vault()  # the post-commit shim sealed
    repo.write("reports/shimmed.csv", "x")
    repo.sh("add", "-f", "reports/shimmed.csv")
    blocked = commit(repo, "blocked by the shim")
    assert blocked.returncode != 0 and "reports/shimmed.csv" in blocked.stderr
    repo.sh("restore", "--staged", "--", "reports/shimmed.csv")
    prune_unreachable(repo)
    assert repo.raw("push", "-q", "origin", "main").returncode == 0
    repo.assert_no_leak(env.bare)


def test_uninstall_removes_only_shims_of_our_exact_shape(env: Env, no_config_hooks: None) -> None:
    repo = env.repo
    hooks_dir = repo.path / ".git" / "hooks"
    assert repo.cli("init").code == 0
    edited = hooks_dir / "post-merge"
    edited.write_bytes(edited.read_bytes() + b"echo my own addition\n")  # no longer our shape
    digest = sha(edited)
    assert repo.cli("init").code == 0
    assert sha(edited) == digest  # a modified shim is treated as foreign, not repaired
    assert repo.cli("uninstall", "--yes").code == 0
    assert not (hooks_dir / "pre-commit").exists() and not (hooks_dir / "post-commit").exists()
    assert edited.exists() and sha(edited) == digest


def test_with_shim_flag_adds_shims_next_to_config_hooks_and_uninstall_takes_both(env: Env) -> None:
    repo = env.repo
    result = repo.cli("init", "--shim")
    assert result.code == 0
    hooks_dir = repo.path / ".git" / "hooks"
    assert all((hooks_dir / e).exists() for e in hooks.EVENTS)
    assert len(config_hooks(repo)) == 10
    assert repo.cli("init").code == 0  # without the flag the shims we own are dropped again
    assert not any((hooks_dir / e).exists() for e in hooks.EVENTS)
    repo.cli("init", "--shim")
    out = repo.cli("uninstall", "--yes").out
    assert "hook shim removed" in out and "config hook removed" in out
    assert config_hooks(repo) == [] and not any((hooks_dir / e).exists() for e in hooks.EVENTS)


def test_shim_is_not_written_into_a_shared_or_versioned_hooks_path(
    env: Env, no_config_hooks: None, tmp_path: Path
) -> None:
    shared = tmp_path / "shared-hooks"
    shared.mkdir()
    env.repo.sh("config", "--local", "core.hooksPath", str(shared))
    result = env.repo.cli("init")
    assert "points outside this repository's .git" in result.err
    assert list(shared.iterdir()) == []
    assert "NOT installed" in result.err
    assert env.repo.cli("doctor").code == 1  # the guard is not in place: a problem, not a pass


# ----------------------------------------------------------------- --no-verify (matrix)


def test_no_verify_matrix(env: Env) -> None:
    repo = env.repo
    assert repo.cli("init").code == 0
    repo.sh("add", "-A")
    assert commit(repo, "base").returncode == 0
    repo.write("reports/n.csv", "n\n")
    repo.write("docs/ok.md", "ok\n")
    repo.sh("add", "-A")
    assert staged(repo) == ["docs/ok.md"]
    assert commit(repo, "add -A + no-verify", "--no-verify").returncode == 0
    assert "reports/n.csv" not in repo.sh("ls-files")
    repo.sh("add", "-f", "reports/n.csv")
    assert commit(repo, "force + no-verify", "--no-verify").returncode == 0
    assert "reports/n.csv" in repo.sh("ls-files")  # the documented hole
    assert repo.raw("push", "origin", "main").returncode != 0  # ... closed again at push time


# ------------------------------------------------------------------- autoUnlock / prompts


def marker_key_command(repo: NbpRepo, marker: Path, *, then: str = "ok") -> None:
    """keyCommand that records that it ran, then behaves like the normal test command."""
    code = (
        "import pathlib, subprocess, sys;"
        f"pathlib.Path({str(marker)!r}).write_text('ran');"
        f"sys.exit(subprocess.call([sys.executable, {str(helpers.KEYCMD)!r}, {then!r}]))"
    )
    repo.set_config("nbp-safe.keyCommand", json.dumps([sys.executable, "-c", code]))


def test_hooks_never_run_the_key_command_by_default(env: Env, tmp_path: Path) -> None:
    repo = env.repo
    marker = tmp_path / "key-command-ran"
    marker_key_command(repo, marker)
    env.agent.stop()  # locked
    assert repo.cli("init").code == 0
    repo.sh("add", "-A")
    result = commit(repo, "locked commit")
    assert result.returncode == 0 and "nbp-git-safe unlock" in result.stderr
    repo.raw("push", "-q", "origin", "main")
    repo.sh("checkout", "-q", "-b", "other")
    assert not marker.exists()  # autoUnlock=false: no hook ever prompts or runs the command


def test_auto_unlock_is_opt_in_and_enables_the_content_check(env: Env, tmp_path: Path) -> None:
    repo = env.repo
    key_env = {helpers.TEST_KEY_ENV: crypto.encode_key(repo.master)}  # the test keyCommand reads it
    marker = tmp_path / "key-command-ran"
    marker_key_command(repo, marker)
    repo.set_config("nbp-safe.autoUnlock", "true")
    env.agent.stop()
    assert repo.cli("init").code == 0
    repo.sh("add", "-A")
    first = commit(repo, "baseline", env=key_env)
    assert first.returncode == 0, first.stderr
    assert marker.exists() and env.has_vault(), first.stderr  # the hook unlocked and sealed
    repo.write("public/c.txt", repo.read(first_protected(repo, ".csv")))
    repo.sh("add", "public/c.txt")
    blocked = commit(repo, "copy", env=key_env)
    assert blocked.returncode != 0 and "same content" in blocked.stderr
    repo.sh("restore", "--staged", "--", "public/c.txt")
    prune_unreachable(repo)
    repo.assert_no_leak(env.bare)


def test_auto_unlock_failure_or_timeout_degrades_to_the_path_check(
    env: Env, tmp_path: Path
) -> None:
    repo = env.repo
    env.agent.stop()
    marker = tmp_path / "ran"
    marker_key_command(repo, marker, then="sleep")
    repo.set_config("nbp-safe.autoUnlock", "true")
    repo.set_config("nbp-safe.keyCommandTimeout", "1")
    assert repo.cli("init").code == 0
    repo.sh("add", "-A")
    slow = commit(repo, "key command hangs")
    assert slow.returncode == 0, slow.stderr
    assert "autoUnlock failed" in slow.stderr and "timed out" in slow.stderr
    marker_key_command(repo, marker, then="exit1")
    repo.write("reports/z.csv", "z")
    repo.sh("add", "-f", "reports/z.csv")
    blocked = commit(repo, "still guarded by path")
    assert blocked.returncode != 0 and "reports/z.csv" in blocked.stderr
    assert "autoUnlock failed" in blocked.stderr


# ---------------------------------------------------------------- init extras


def test_init_gitignore_block_is_optional_generic_and_removable(env: Env) -> None:
    repo = env.repo
    (repo.path / ".git" / "info" / "nbp-safe").write_text("local-only-secret/\n")
    repo.write(".gitignore", "node_modules/\n")
    assert "gitignore block" not in repo.cli("init").err
    assert "nbp-git-safe managed" not in (repo.path / ".gitignore").read_text()
    result = repo.cli("init", "--gitignore-block")
    assert ".gitignore block installed" in result.err
    text = (repo.path / ".gitignore").read_text()
    assert text.startswith("node_modules/\n") and "reports/" in text and "*.nbp-tmp" in text
    assert "local-only-secret" not in text  # local patterns never go into a versioned file
    assert "already up to date" in repo.cli("init", "--gitignore-block").err
    out = repo.cli("uninstall", "--yes").out
    assert ".gitignore block removed" in out
    assert (repo.path / ".gitignore").read_text() == "node_modules/\n"


def test_init_warns_about_name_like_patterns_without_failing(env: Env) -> None:
    env.repo.write(".nbp-safe", "reports/\nMaria Silva/\nfulano@example.invalid\n")
    result = env.repo.cli("init")
    assert result.code == 0
    assert result.err.count("looks like") == 2 and "Maria" not in result.err


def test_init_no_hooks_flag(env: Env) -> None:
    result = env.repo.cli("init", "--no-hooks")
    assert result.code == 0 and "git config hooks" not in result.err
    assert config_hooks(env.repo) == []


# ------------------------------------------------------------------------ uninstall


def test_uninstall_confirmation_flow_and_what_it_never_touches(
    env: Env, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = env.repo
    assert repo.cli("init").code == 0
    repo.sh("add", "-A")
    assert commit(repo, "base").returncode == 0
    tip = env.tip()
    files = {
        p.relative_to(repo.path).as_posix(): p.read_bytes()
        for p in (repo.path / "reports").rglob("*")
        if p.is_file()
    }
    refused = repo.cli("uninstall")  # no terminal, no --yes
    assert refused.code == 1 and "confirmation" in refused.err and config_hooks(repo)

    class FakeTty:
        def isatty(self) -> bool:
            return True

    monkeypatch.setattr(sys, "stdin", FakeTty())
    monkeypatch.setattr("builtins.input", lambda _prompt="": "no")
    wrong = repo.cli("uninstall")
    assert wrong.code == 1 and "not confirmed" in wrong.err and config_hooks(repo)
    monkeypatch.setattr("builtins.input", lambda _prompt="": "uninstall")
    done = repo.cli("uninstall")
    assert done.code == 0 and "exclude block removed" in done.out
    assert config_hooks(repo) == []
    assert env.tip() == tip  # the vault branch is untouched ...
    assert {
        p.relative_to(repo.path).as_posix(): p.read_bytes()
        for p in (repo.path / "reports").rglob("*")
        if p.is_file()
    } == files  # ... and so are the plaintext files
    assert "nothing of ours" in repo.cli("uninstall", "--yes").out
    assert "reports/" in repo.sh("status", "--porcelain")  # visible to git again


def test_uninstall_outside_a_repository_fails_cleanly(tmp_path: Path, isolated_git: object) -> None:
    from tests.integration.test_cli_basic import run

    code, _, err = run("-C", str(tmp_path), "uninstall", "--yes")
    assert code == 1 and "not inside a git work tree" in err
