# SPDX-License-Identifier: MIT
"""Audit of 2026-10-10 (agy, finding 4; Codex lead on the keyCommand's stderr): the children of
this tool (git, the keyCommand) get an allow-listed environment, never a token they do not need,
and an unattended keyCommand failure is reported without echoing what it printed. Every value here
is a throw-away string generated by the test; no password manager is involved."""

from __future__ import annotations

import os
import secrets
import stat
import sys
from pathlib import Path

import pytest

from nbp_git_safe import gitutil, unlock
from tests.helpers import KEYCMD


def _fake_token() -> str:
    return "ops_" + secrets.token_urlsafe(32)  # shaped like a service-account token, but random


def test_minimal_env_keeps_what_git_needs_and_drops_tokens() -> None:
    token = _fake_token()
    env = {
        "PATH": "/usr/bin",
        "HOME": "/home/x",
        "LANG": "C.UTF-8",
        "LC_ALL": "C",
        "GIT_DIR": "/repo/.git",
        "GIT_CONFIG_GLOBAL": "/dev/null",
        "SSH_AUTH_SOCK": "/run/user/1000/agent.sock",
        "NBP_SAFE_RUNTIME_DIR": "/run/user/1000/rt",
        "GH_TOKEN": "gh-helper-needs-it",
        "OP_SERVICE_ACCOUNT_TOKEN": token,
        "op_session_x": token,
        "AWS_SECRET_ACCESS_KEY": token,
        "MY_APP_PASSWORD": token,
    }
    kept = gitutil.child_env(env)
    assert token not in kept.values()
    for name in ("PATH", "HOME", "LANG", "LC_ALL", "GIT_DIR", "GIT_CONFIG_GLOBAL", "SSH_AUTH_SOCK"):
        assert kept[name] == env[name]
    assert (
        kept["NBP_SAFE_RUNTIME_DIR"] == "/run/user/1000/rt"
        and kept["GH_TOKEN"] == "gh-helper-needs-it"
    )
    assert kept[gitutil.NO_CWD_EXE] == "1"


def test_pass_env_adds_names_but_never_op_for_git() -> None:
    token = _fake_token()
    env = {
        "PATH": "/usr/bin",
        "AWS_PROFILE": "backup",
        "OP_SERVICE_ACCOUNT_TOKEN": token,
        gitutil.PASS_ENV: "aws_profile, OP_SERVICE_ACCOUNT_TOKEN",
    }
    kept = gitutil.child_env(env)
    assert kept["AWS_PROFILE"] == "backup"
    assert "OP_SERVICE_ACCOUNT_TOKEN" not in kept  # git never gets OP_*
    wrapper = gitutil.key_command_env("/usr/local/bin/get-key.sh", env)
    assert wrapper["OP_SERVICE_ACCOUNT_TOKEN"] == token  # listed: a wrapper that runs op


@pytest.mark.parametrize(
    ("argv0", "gets_op"),
    [
        ("op", True),
        ("/usr/bin/op", True),
        (r"C:\Program Files\1Password CLI\op.exe", True),
        ("OP.EXE", True),
        (sys.executable, False),
        ("/usr/bin/opx", False),
        ("bash", False),
    ],
)
def test_key_command_env_gives_op_variables_only_to_op(argv0: str, gets_op: bool) -> None:
    token = _fake_token()
    env = {"PATH": "/usr/bin", "OP_SERVICE_ACCOUNT_TOKEN": token, "OP_ACCOUNT": "acct"}
    got = gitutil.key_command_env(argv0, env)
    assert got["PATH"] == "/usr/bin"
    assert ("OP_SERVICE_ACCOUNT_TOKEN" in got) is gets_op
    assert ("OP_ACCOUNT" in got) is gets_op


def test_a_real_git_child_does_not_see_the_token(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    token = _fake_token()
    monkeypatch.setenv("OP_SERVICE_ACCOUNT_TOKEN", token)
    monkeypatch.setenv("SOME_OTHER_SECRET", token)
    git = gitutil.Git(tmp_path)
    out = git.text("-c", "alias.showenv=!env", "showenv")  # git runs the alias with its own env
    assert "PATH=" in out
    assert token not in out
    assert "OP_SERVICE_ACCOUNT_TOKEN" not in out


def test_a_python_key_command_does_not_see_op_variables(
    master_key: bytes, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("OP_SERVICE_ACCOUNT_TOKEN", _fake_token())
    assert unlock.run_key_command([sys.executable, str(KEYCMD), "no-op-env"], 30) == master_key


@pytest.mark.skipif(sys.platform == "win32", reason="a fake `op` is a POSIX script here")
def test_a_key_command_that_is_op_gets_the_op_variables(
    master_key: bytes, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A FAKE `op` (a script written by the test): it prints the test key only when the
    throw-away token reached it. The real 1Password CLI is never run."""
    token = _fake_token()
    monkeypatch.setenv("OP_SERVICE_ACCOUNT_TOKEN", token)
    fake = tmp_path / "op"
    fake.write_text(
        f"#!{sys.executable}\n"
        "import os, sys\n"
        f"ok = os.environ.get('OP_SERVICE_ACCOUNT_TOKEN') == {token!r}\n"
        "sys.stdout.write(os.environ['NBP_SAFE_TEST_KEY'] + '\\n' if ok else '')\n"
        "sys.exit(0 if ok else 4)\n",
        encoding="utf-8",
    )
    fake.chmod(fake.stat().st_mode | stat.S_IXUSR)
    assert unlock.run_key_command([str(fake), "document", "get", "x"], 30) == master_key


def test_an_unattended_failure_quotes_stderr_redacted(
    master_key: bytes, monkeypatch: pytest.MonkeyPatch, capfd: pytest.CaptureFixture[str]
) -> None:
    noise = secrets.token_urlsafe(32)
    monkeypatch.setenv("NBP_SAFE_TEST_NOISE", noise)
    monkeypatch.setenv("NBP_SAFE_NONINTERACTIVE", "1")
    with pytest.raises(unlock.KeyCommandError) as exc:
        unlock.run_key_command([sys.executable, str(KEYCMD), "noisy-fail"], 30)
    message = str(exc.value)
    assert "exit code 1" in message and "boom" in message and "[redacted]" in message
    assert noise not in message
    assert noise not in capfd.readouterr().err  # captured, not passed through
    # at a terminal the command speaks to the person directly; the message stays generic
    monkeypatch.setenv("NBP_SAFE_NONINTERACTIVE", "0")
    with pytest.raises(unlock.KeyCommandError) as exc:
        unlock.run_key_command([sys.executable, str(KEYCMD), "noisy-fail"], 30)
    assert "boom" not in str(exc.value)
    assert "boom" in capfd.readouterr().err


def test_redact_keeps_short_words_and_hides_long_runs() -> None:
    key_like = secrets.token_urlsafe(64)
    out = unlock.redact(f"line1\nline2\n[ERROR] 401 unauthorized: {key_like}\n\n")
    assert key_like not in out and "[redacted]" in out and "401 unauthorized" in out
    assert len(unlock.redact("x" * 5000 + " y")) <= unlock.MAX_ERROR_QUOTE
    assert os.linesep not in unlock.redact("a\nb\nc\nd")
